#import "../components/post/types.gql"

type Query {
  hello: String!
  getAllPosts: [Post!]
  getPostById(id: ID!): Post
}

type Mutation {
  signUp(userName: String!, email: String!, password: String!): String!
  login(email: String!, password: String!): String!
  createPost(title: String!, content: String!, author: String!): ID!
}